package instituteerp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Admin
 */
public class RegistrationPage extends javax.swing.JFrame {
String gender;
    /**
     * Creates new form registration
     */
    public RegistrationPage() {
        initComponents();
    }
    public void reset()
    {
        txname.setText("");
        register.setSelectedIndex(0);
        jcgender.setSelectedIndex(0);
        txemail.setText("");
        txmobile.setText("");
        txpassword.setText("");
        txuname.setText("");
        txcnfpass.setText("");
        
               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btclear = new javax.swing.JButton();
        btloginpage = new javax.swing.JButton();
        btsubmit = new javax.swing.JButton();
        txpassword = new javax.swing.JPasswordField();
        txname = new javax.swing.JTextField();
        txuname = new javax.swing.JTextField();
        txemail = new javax.swing.JTextField();
        jcgender = new javax.swing.JComboBox<>();
        txmobile = new javax.swing.JTextField();
        register = new javax.swing.JComboBox<>();
        txcnfpass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registration-online-membership-network-internet-business-technology-concept-104512007.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 5, 187, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 514, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("                        Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 175, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("                  Username :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 175, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("                         Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 175, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("                      Gender :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 175, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("                  Mobile No :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, 157, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("                    Register :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, 175, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("                  Password :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 175, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("     Confirm Password :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 391, 176, 30));

        btclear.setBackground(new java.awt.Color(204, 255, 204));
        btclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btclear.setForeground(new java.awt.Color(0, 0, 204));
        btclear.setText("CLEAR");
        btclear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });
        jPanel1.add(btclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 454, 71, 27));

        btloginpage.setBackground(new java.awt.Color(204, 204, 255));
        btloginpage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btloginpage.setForeground(new java.awt.Color(153, 0, 153));
        btloginpage.setText("LOGIN_P");
        btloginpage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btloginpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginpageActionPerformed(evt);
            }
        });
        jPanel1.add(btloginpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 454, 65, 28));

        btsubmit.setBackground(new java.awt.Color(255, 204, 204));
        btsubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btsubmit.setForeground(new java.awt.Color(51, 153, 0));
        btsubmit.setText("SUBMIT");
        btsubmit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 454, 72, 27));

        txpassword.setBackground(new java.awt.Color(255, 51, 51));
        txpassword.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txpassword.setBorder(null);
        jPanel1.add(txpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 340, 297, 25));

        txname.setBackground(new java.awt.Color(255, 51, 51));
        txname.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txname.setBorder(null);
        txname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnameActionPerformed(evt);
            }
        });
        jPanel1.add(txname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 53, 296, 30));

        txuname.setBackground(new java.awt.Color(255, 51, 51));
        txuname.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txuname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txuname.setBorder(null);
        jPanel1.add(txuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 118, 297, 29));

        txemail.setBackground(new java.awt.Color(255, 51, 51));
        txemail.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txemail.setBorder(null);
        jPanel1.add(txemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 174, 297, 29));

        jcgender.setBackground(new java.awt.Color(255, 51, 51));
        jcgender.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jcgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jcgender.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jcgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 226, 97, 24));

        txmobile.setBackground(new java.awt.Color(255, 51, 51));
        txmobile.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txmobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txmobile.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(txmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 268, 297, 26));

        register.setBackground(new java.awt.Color(255, 51, 51));
        register.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        register.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "User" }));
        register.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 314, 103, 23));

        txcnfpass.setBackground(new java.awt.Color(255, 51, 51));
        txcnfpass.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txcnfpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txcnfpass.setBorder(null);
        jPanel1.add(txcnfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 391, 296, 26));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 89, 297, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 153, 297, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 208, 297, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 298, 297, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 373, 296, 7));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 421, 296, 6));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 510, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnameActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btclearActionPerformed

    private void btloginpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginpageActionPerformed
        // TODO add your handling code here:
         new LoginPage().setVisible(true);
              dispose();
    }//GEN-LAST:event_btloginpageActionPerformed

    private void btsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubmitActionPerformed
        // TODO add your handling code here:
        String p_name = txname.getText();
        String p_uname = txuname.getText();
        String p_email = txemail.getText();
        String p_gender = jcgender.getItemAt(jcgender.getSelectedIndex());
        String p_mobile = txmobile.getText();
        String p_rg = register.getItemAt(register.getSelectedIndex());
        String p_pass = txpassword.getText();
        String p_cpass = txcnfpass.getText();
        
       int i = databasec.setAllDetails(p_name,p_uname,p_email,p_gender,p_mobile,p_rg,p_pass,p_cpass);
       if(i==1)
       {
           JOptionPane.showMessageDialog(this, "Data Inserted Successfully");
           
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Data not inserted");
           
       }
        
        reset();
    }//GEN-LAST:event_btsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclear;
    private javax.swing.JButton btloginpage;
    private javax.swing.JButton btsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox<String> jcgender;
    private javax.swing.JComboBox<String> register;
    private javax.swing.JPasswordField txcnfpass;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txmobile;
    private javax.swing.JTextField txname;
    private javax.swing.JPasswordField txpassword;
    private javax.swing.JTextField txuname;
    // End of variables declaration//GEN-END:variables
}
